# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.PositiveIntegerField(verbose_name='Estrelas')),
                ('nota', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota')),
                ('alunos_sem_camisa', models.PositiveIntegerField(default=0, verbose_name='Alunos sem camiseta do porteira')),
                ('ocorrencias', models.TextField(blank=True, null=True, verbose_name='Ocorrências')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
    ]
