# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_projeto_avaliador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='avaliador',
        ),
        migrations.AddField(
            model_name='projeto',
            name='avaliador',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
