# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171120_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliador',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='avaliador',
            field=models.ManyToManyField(to='core.Avaliador'),
        ),
    ]
