# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171120_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estrelas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estrelas'),
        ),
    ]
